batch_size: 2048
beta: 0.1
continue_from: ckp/edac-walker2d-medium-expert-230227-200026/edac-499.pt
device: cuda
env: walker2d-medium-expert
epochs: 1000
eta: 1.0
eval_episodes: 5
gamma: 0.99
group: edac
lr_actor: 0.0003
lr_critic: 0.0003
name: edac
num_critics: 5
project: edac_reimplementation
save_every: 10
save_path: ckp
seed: 27050
tau: 0.005
updates_per_epoch: 500
