batch_size: 2048
beta: 0.1
continue_from: ckp/edac-halfcheetah-medium-v2-230227-135107/edac-999.pt
device: cuda
env: halfcheetah-medium-v2
epochs: 1300
eta: 1.0
eval_episodes: 5
gamma: 0.99
group: edac
lr_actor: 0.0003
lr_critic: 0.0003
name: edac
num_critics: 5
project: edac_reimplementation
save_every: 10
save_path: ckp
seed: 72169
tau: 0.005
updates_per_epoch: 500
